//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAC_ZoneControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\XBMC\\audio\\RepeaterDen.exe")]
        public string RepeaterDen {
            get {
                return ((string)(this["RepeaterDen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\XBMC\\audio\\RepeaterKitchen.exe")]
        public string RepeaterKitchen {
            get {
                return ((string)(this["RepeaterKitchen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\XBMC\\audio\\RepeaterDining.exe")]
        public string RepeaterDining {
            get {
                return ((string)(this["RepeaterDining"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\XBMC\\audio\\RepeaterLiving.exe")]
        public string RepeaterLiving {
            get {
                return ((string)(this["RepeaterLiving"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\XBMC\\audio\\RepeaterOutsideHouse.exe")]
        public string RepeaterOutsideHouse {
            get {
                return ((string)(this["RepeaterOutsideHouse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\XBMC\\audio\\RepeaterOutsideFence.exe")]
        public string RepeaterOutsideFence {
            get {
                return ((string)(this["RepeaterOutsideFence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z1 (2- kX 10k2 Audio (3550) - G")]
        public string RepeaterDeviceZoneDen {
            get {
                return ((string)(this["RepeaterDeviceZoneDen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z2 (2- kX 10k2 Audio (3550) - G")]
        public string RepeaterDeviceZoneKitchen {
            get {
                return ((string)(this["RepeaterDeviceZoneKitchen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z3 (2- kX 10k2 Audio (3550) - G")]
        public string RepeaterDeviceZoneDining {
            get {
                return ((string)(this["RepeaterDeviceZoneDining"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z4 (kX 10k2 Audio (3550) - Gene")]
        public string RepeaterDeviceZoneLiving {
            get {
                return ((string)(this["RepeaterDeviceZoneLiving"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z5 (kX 10k2 Audio (3550) - Gene")]
        public string RepeaterDeviceZoneOutsideHouse {
            get {
                return ((string)(this["RepeaterDeviceZoneOutsideHouse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z6 (kX 10k2 Audio (3550) - Gene")]
        public string RepeaterDeviceZoneOutsideFence {
            get {
                return ((string)(this["RepeaterDeviceZoneOutsideFence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Line 1 (Virtual Audio Cable)")]
        public string DeviceSourceDefault {
            get {
                return ((string)(this["DeviceSourceDefault"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kX Wave SB0350 10k2 [8000] 0/1")]
        public string DeviceSourceIPod {
            get {
                return ((string)(this["DeviceSourceIPod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kX Wave SB0350 10k2 [8800] 0/1")]
        public string DeviceSourceTurntable {
            get {
                return ((string)(this["DeviceSourceTurntable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NVIDIA(R) nForce(TM) Audio")]
        public string DeviceSourceLineIn {
            get {
                return ((string)(this["DeviceSourceLineIn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int RepeaterBitsPerSample {
            get {
                return ((int)(this["RepeaterBitsPerSample"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RepeaterChannels {
            get {
                return ((int)(this["RepeaterChannels"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int RepeaterBufferMS {
            get {
                return ((int)(this["RepeaterBufferMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RepeaterBuffers {
            get {
                return ((int)(this["RepeaterBuffers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NVIDIA(R) nForce(TM) Audio")]
        public string DeviceZoneTelevision {
            get {
                return ((string)(this["DeviceZoneTelevision"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\xbmc\\Audio\\RepeaterTelevision.exe")]
        public string RepeaterTelevision {
            get {
                return ((string)(this["RepeaterTelevision"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kX Control SB0350 10k2 [8000]")]
        public string kxDevice1 {
            get {
                return ((string)(this["kxDevice1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kX Control SB0350 10k2 [8800]")]
        public string kxDevice2 {
            get {
                return ((string)(this["kxDevice2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChannelDen {
            get {
                return ((int)(this["ChannelDen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChannelKitchen {
            get {
                return ((int)(this["ChannelKitchen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ChannelDining {
            get {
                return ((int)(this["ChannelDining"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChannelLiving {
            get {
                return ((int)(this["ChannelLiving"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChannelOutsideHouse {
            get {
                return ((int)(this["ChannelOutsideHouse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ChannelOutsideFence {
            get {
                return ((int)(this["ChannelOutsideFence"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int VolumeDen {
            get {
                return ((int)(this["VolumeDen"]));
            }
            set {
                this["VolumeDen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int VolumeKitchen {
            get {
                return ((int)(this["VolumeKitchen"]));
            }
            set {
                this["VolumeKitchen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int VolumeDining {
            get {
                return ((int)(this["VolumeDining"]));
            }
            set {
                this["VolumeDining"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int VolumeLiving {
            get {
                return ((int)(this["VolumeLiving"]));
            }
            set {
                this["VolumeLiving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VolumeOutsideHouse {
            get {
                return ((int)(this["VolumeOutsideHouse"]));
            }
            set {
                this["VolumeOutsideHouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VolumeOutsideFence {
            get {
                return ((int)(this["VolumeOutsideFence"]));
            }
            set {
                this["VolumeOutsideFence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z1")]
        public string PlaybackDeviceZoneDen {
            get {
                return ((string)(this["PlaybackDeviceZoneDen"]));
            }
            set {
                this["PlaybackDeviceZoneDen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z2")]
        public string PlaybackDeviceZoneKitchen {
            get {
                return ((string)(this["PlaybackDeviceZoneKitchen"]));
            }
            set {
                this["PlaybackDeviceZoneKitchen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z3")]
        public string PlaybackDeviceZoneDining {
            get {
                return ((string)(this["PlaybackDeviceZoneDining"]));
            }
            set {
                this["PlaybackDeviceZoneDining"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z4")]
        public string PlaybackDeviceZoneLiving {
            get {
                return ((string)(this["PlaybackDeviceZoneLiving"]));
            }
            set {
                this["PlaybackDeviceZoneLiving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z5")]
        public string PlaybackDeviceZoneOutsideHouse {
            get {
                return ((string)(this["PlaybackDeviceZoneOutsideHouse"]));
            }
            set {
                this["PlaybackDeviceZoneOutsideHouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z6")]
        public string PlaybackDeviceZoneOutsideFence {
            get {
                return ((string)(this["PlaybackDeviceZoneOutsideFence"]));
            }
            set {
                this["PlaybackDeviceZoneOutsideFence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlaybackDeviceZoneTelevision {
            get {
                return ((string)(this["PlaybackDeviceZoneTelevision"]));
            }
            set {
                this["PlaybackDeviceZoneTelevision"] = value;
            }
        }
    }
}
